-- Enable Row Level Security on all public tables to lock down the
-- PostgREST anon/authenticated surface in Supabase. The application
-- connects as the `postgres` role (BYPASSRLS), so server-side Drizzle
-- queries are unaffected. With RLS enabled and no policies, anon and
-- authenticated requests return zero rows.
ALTER TABLE "account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "api_token" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "execution" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "execution_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fn" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fn_ai_context" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fn_asset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fn_comment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fn_draft" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fn_fork" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fn_marketplace_profile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fn_star" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fn_version" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fn_version_asset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "function_git_binding" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "github_connection_audit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "github_installation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "github_repo_access" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "invitation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "member" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "organization" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "plan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "secret" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "subscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "trigger" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "usage_event" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "verification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "webhook_event" ENABLE ROW LEVEL SECURITY;
